### ISSUE TITLE
Can't build on Windows without cuda

### ISSUE THREAD

**Issue by twchapman** [conda-forge/kaldi-feedstock#41]
### Comment:

I'm trying to `conda-build kaldi-feedstock` and running into trouble. It complained about `cuda_compiler_version` not being set:, and I tried to set it in a few places but must be doing it wrong.
`Error: Failed to render jinja template in D:\conda-builds\kaldi-feedstock\recipe\meta.yaml: 'cuda_compiler_version' is undefined`

Instead, I hardcoded a few places to false (I only want CPU processing). However, it's now failing because it can't find a python package it seems, and I haven't been able to get around it:
```D:\conda-builds>conda-build kaldi-feedstock
C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Scripts\conda-build-script.py:10: DeprecationWarning: conda_build.cli.main_build.main is deprecated and will be removed in 4.0.0. Use `conda build` instead.
  sys.exit(main())
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
Adding in variants from internal_defaults
Adding in variants from D:\conda-builds\kaldi-feedstock\recipe\conda_build_config.yaml
Attempting to finalize metadata for kaldi
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\conda-bld\work
  Test:
 C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\conda-bld\test_tmp
Leaving build/test environments:
  Test:
source activate  C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\conda-bld\_test_env
  Build:
source activate  C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\conda-bld\_build_env


Traceback (most recent call last):
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\environ.py", line 900, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda\common\io.py", line 84, in decorated
    return f(*args, **kwds)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda\plan.py", line 535, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda\core\solve.py", line 154, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(
                               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda\core\solve.py", line 215, in solve_for_diff
    final_precs = self.solve_final_state(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda\core\solve.py", line 380, in solve_final_state
    ssc = self._add_specs(ssc)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda\core\solve.py", line 733, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda\resolve.py", line 653, in _get_package_pool
    pool = self.get_reduced_index(specs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda\common\io.py", line 84, in decorated
    return f(*args, **kwds)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda\resolve.py", line 678, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda\resolve.py", line 333, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - cuda_win-64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\deprecations.py", line 70, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\cli\main_build.py", line 589, in main
    execute(sys.argv[1:])
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\cli\main_build.py", line 568, in execute
    outputs = api.build(
              ^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\api.py", line 253, in build
    return build_tree(
           ^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\build.py", line 3804, in build_tree
    packages_from_this = build(
                         ^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\build.py", line 2474, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\render.py", line 923, in expand_outputs
    for output_dict, m in deepcopy(_m).get_output_metadata_set(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\metadata.py", line 2565, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\metadata.py", line 909, in finalize_outputs_pass
    fm = finalize_metadata(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\render.py", line 637, in finalize_metadata
    build_unsat, host_unsat = add_upstream_pins(
                              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\render.py", line 452, in add_upstream_pins
    build_deps, build_unsat, extra_run_specs_from_build = _read_upstream_pin_files(
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\render.py", line 431, in _read_upstream_pin_files
    deps, actions, unsat = get_env_dependencies(
                           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\render.py", line 151, in get_env_dependencies
    actions = environ.get_install_actions(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t.chapman\AppData\Local\anaconda3\envs\mfa-dev\Lib\site-packages\conda_build\environ.py", line 902, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {'cuda_win-64'}
```

Am I just missing something?

**Comment by h-vetinari** [comment]
> Am I just missing something?

The first question that comes to my mind is: why are do you need to rebuild this yourself, rather than just installing the builds from conda-forge? 🤔 

This feedstock comes with many different combinations (corresponding to the different architectures we support), and the one you want to use is [`win_64_cuda_compilerNonecuda_compiler_versionNone.yaml`](https://github.com/conda-forge/kaldi-feedstock/blob/main/.ci_support/win_64_cuda_compilerNonecuda_compiler_versionNone.yaml).

So already now,
```
cd kaldi-feedstock
conda build -m .ci_support\win_64_cuda_compilerNonecuda_compiler_versionNone.yaml recipe
```
should work.

**Comment by twchapman** [comment]
> The first question that comes to my mind is: why are do you need to rebuild this yourself, rather than just installing the builds from conda-forge? 🤔

Fair question! I'm actually trying to decipher how Kaldi is being built through this module, because the instructions I'd seen for getting Kaldi built on windows were much more complicated than a single command, and I was hoping to better understand how things are being generated.

I'm also trying to do some development with the Montreal Forced Aligner, and am trying to better understand the ecosystem in general.

Looks like that command got me going, I probably should have dug into the docs a bit more. I'm running into some compiler issues but I can try and debug those myself. Thanks so much for the expedient help!
